final Map<String, String> es = {


  // ── Login Screen ──
  'okr_logo':                   'Logo OKR',
  'bottom_logo':                'Logo inferior',
  'rejoin_operation':           'Reincorpórate a la Operación',
  'strategy_awaits':            'Tu estrategia te espera. Inicia sesión para continuar.',
  'enter_email':                'Ingresa tu correo electrónico',
  'enter_password':             'Ingresa tu contraseña',
  'remember_me':                'Recuérdame',
  'forget_password':            '¿Olvidaste tu contraseña?',
  'sign_in':                    'Iniciar sesión',
  'continue_with_google':       'Continuar con Google',
  'want_a_navigator':           '¿No tienes una cuenta?',
  'sign_up':                    'Registrarse',
  'password_reset_coming':      '¡El restablecimiento de contraseña estará disponible pronto!',

  // ── Register Screen ──
  'enter_arena':                'Entra a la Arena',
  'sign_up_navigator':          'Regístrate y conviértete en un Navegador. Lleva a tu equipo a la victoria.',
  'enter_name':                 'Ingresa tu nombre completo',
  'enter_phone':                'Ingresa tu número de teléfono',
  'confirm_password':           'Confirma tu contraseña',
  'name_required':              'El nombre es obligatorio',
  'already_have_account':       '¿Ya eres un Navegador?',

  // ── Forgot Password Screen ──
  'forgot_password':            'Olvidé mi contraseña',
  'enter_email_address':        'Ingresa tu dirección de correo electrónico',
  'we_will_send_otp':           'Te enviaremos un código OTP de 6 dígitos para restablecer tu contraseña.',
  'enter_email_hint':           'Ingresa el correo electrónico',
  'send_otp':                   'Enviar código OTP',

  // ── OTP Verification Screen ──
  'verify_otp':                 'Verificar OTP',
  'verify_otp_title':           'Ingresa el código OTP',
  'otp_sent_to':                'Se ha enviado un código de 6 dígitos a',
  'time_remaining':             'Tiempo restante:',
  'otp_expired':                'Código OTP expirado',
  'resend_otp':                 'Reenviar código OTP',
  'did_not_receive_code':       '¿No recibiste el código?',

  // ── Reset Password Screen ──
  'reset_password':             'Restablecer contraseña',
  'create_new_password':        'Crea una nueva contraseña',
  'password_requirements':      'Asegúrate de que tenga al menos 6 caracteres.',
  'enter_new_password_hint':    'Ingresa la nueva contraseña',
  'confirm_password_hint':      'Confirma la nueva contraseña',
  'please_confirm_password':    'Por favor confirma tu contraseña',
  'passwords_do_not_match':     'Las contraseñas no coinciden',
  'reset_password_button':      'Restablecer contraseña',

  // ── Profile Screen ──
  'my_profile':                 'Mi Perfil',
  'view_manage_profile':        'Consulta y gestiona la información de tu perfil.',
  'edit_profile':               'Editar perfil',
  'update_profile':             'Actualizar perfil',
  'logout':                     'Cerrar sesión',
  'cancel':                     'Cancelar',
  'select_profile_image':       'Seleccionar imagen de perfil',
  'enter_email_label':          'Correo electrónico',

  // ── Validation ──
  'phone_required':             'El número de teléfono es obligatorio',
  'email_invalid':              'Por favor ingresa un correo electrónico válido',
  'password_too_short':         'La contraseña debe tener al menos 6 caracteres',
  'password_mismatch':          'Las contraseñas no coinciden',

  'okr_logo':                      'Logo OKR',
  'mask_group':                    'Ilustración del equipo',
  'welcome_team':                  'Bienvenido al\nModo Equipo',
  'splash_team_subtitle':          'Colabora con tu equipo, establece OKRs compartidos y alcanza metas juntos.',
  'team_setup':                    'Configuración del equipo',

// ── CreateTeamScreen ──────────────────────────────────────────
  'team_mode':                     'Modo Equipo',
  'create_new_team':               'Crear nuevo equipo',
  'edit_team':                     'Editar equipo',
  'team_info_label':               'Información del equipo',
  'team_name_label':               'Nombre del equipo',
  'team_mission_label':            'Misión del equipo',
  'enter_team_name':               'Ingresa el nombre del equipo…',
  'describe_your_team_mission':    'Describe la misión de tu equipo…',
  'choose_team_avatar':            'Elegir avatar del equipo',
  'join_existing_team':            'Unirse a un equipo existente',
  'team_code':                     '¿Tienes un código de equipo? Ingrésalo abajo para unirte.',
  'enter_team_code':               'Ingresa el código del equipo…',
  'join_team':                     'Unirse al equipo',
  'continue':                      'Continuar',
  'save_changes':                  'Guardar cambios',
  'saving':                        'Guardando…',
  'creating':                      'Creando…',
  'loading':                       'Cargando…',
  'create':                        'Crear',
  'new_team':                      'Nuevo equipo',

// ── TeamLobbyScreen ───────────────────────────────────────────
  'lobby':                         'Sala de espera',
  'loading_team_details':          'Cargando detalles del equipo…',
  'retry':                         'Reintentar',
  'waiting_for_player':            'Esperando jugador…',
  'invite_someone_to_join':        'Invita a alguien a unirse',
  'team_code_label':               'Código de equipo:',
  'waiting_for_others_to_join':    'Esperando a los demás…',
  'members_joined_label':          '@count miembros unidos',
  'start_game_minimum_players':    'Se necesitan mínimo 2 jugadores para empezar',
  'unknown_user':                  'Usuario desconocido',
  'begin_mission':                 'Iniciar misión',
  'host_only_begin_mission':       'Solo el anfitrión puede iniciar la misión',
  'inviting':                      'Invitando…',
  'invite_members':                'Invitar miembros',
  'shareable_team_link_title':     'Compartir enlace',
  'shareable_team_link_body':      'Comparte este enlace con tus compañeros de equipo',
  'team_code_copied_clipboard':    '¡Enlace copiado al portapapeles!',
  'done':                          'Listo',

// ── CustomRankContainer ───────────────────────────────────────
  'level_points_label':            'Nivel @level | @points Puntos ganados',
  'team_mode':                    'Modo Equipo',
  'lobby':                        'Sala de espera',
  'loading_team_details':         'Cargando detalles del equipo…',
  'retry':                        'Reintentar',
  'waiting_for_player':           'Esperando jugador…',
  'invite_someone_to_join':       'Invita a alguien a unirse',
  'team_code_label':              'Código de equipo:',
  'waiting_for_others_to_join':   'Esperando a los demás…',
  'members_joined_label':         '@count miembros unidos',
  'start_game_minimum_players':   'Se necesitan mínimo 2 jugadores para empezar',
  'unknown_user':                 'Usuario desconocido',
  'begin_mission':                'Iniciar misión',
  'host_only_begin_mission':      'Solo el anfitrión puede iniciar la misión',
  'inviting':                     'Invitando…',
  'invite_members':               'Invitar miembros',
  'shareable_team_link_title':    'Compartir enlace',
  'shareable_team_link_body':     'Comparte este enlace con tus compañeros de equipo',
  'team_code_copied_clipboard':   '¡Enlace copiado al portapapeles!',
  'done':                         'Listo',
// AppBar
  'team_mode':              'Modo Equipo',
  'create_new_team':        'Crear Nuevo Equipo',
  'edit_team':              'Editar Equipo',

  // Section labels
  'team_info_label':        'Información del Equipo',
  'team_name_label':        'Nombre del Equipo',
  'team_mission_label':     'Misión del Equipo',

  // Fields
  'enter_team_name':        'Ingresa el nombre del equipo…',
  'describe_your_team_mission': 'Describe la misión de tu equipo…',
  'choose_team_avatar':     'Elegir Avatar del Equipo',

  // Join team section
  'join_existing_team':     'Unirse a un Equipo Existente',
  'team_code':              '¿Tienes un código de equipo? Ingrésalo abajo para unirte.',
  'enter_team_code':        'Ingresa el código del equipo…',
  'join_team':              'Unirse al Equipo',

  // Buttons
  'continue':               'Continuar',
  'save_changes':           'Guardar Cambios',
  'saving':                 'Guardando…',
  'creating':               'Creando…',
  'loading':                'Cargando…',

  // Header
  'create':                 'Crear',
  'new_team':               'Nuevo Equipo',
// ── CustomAIAnalysisScreen2
  'custom':                         'Personalizado',
  'analysis':                       'Análisis',
  'ai_insights_title':              'Perspectivas IA',
  'ai_insights_description':        'Tu análisis de rendimiento impulsado por IA está listo. Revisa las perspectivas a continuación para entender cómo tu estrategia OKR se alinea con tus objetivos.',
  'proceed':                        'Continuar',

  // ── TeamStrategicArchitectScreen2
  'game':                           'Juego',
  'complete':                       '¡Completado!',
  'strategic_architect':            'Arquitecto Estratégico',
  'strategic_architect_desc':       '¡Excelente pensamiento estratégico y habilidades de adaptación!',
  'strategy_selection':             'Selección de estrategia',
  'objective_selection':            'Selección de objetivo',
  'key_result_selection':           'Selección de resultados clave',
  'initiatives_suggestion':         'Sugerencia de iniciativas',
  'result_performance':             'Rendimiento de resultados',
  'strategic_thinker':              'Pensador Estratégico',
  'master_adapter':                 'Adaptador Maestro',
  'play_again':                     'Jugar de nuevo',
  'view_badges':                    'Ver insignias',
  'share_score':                    'Compartir puntuación',
  'view_your_journey':              'Ver tu recorrido',

  // ── TeamStrategyJourneyScreen
  'strategic':                      'Estratégico',
  'journey':                        'Recorrido',
  'key_strengths':                  'Fortalezas clave',
  'growth_opportunities':           'Oportunidades de crecimiento',
  'go_to_dashboard':                'Ir al panel',
  'bonus_case_study_mode':          'Modo estudio de caso bonus',

  // ── TeamStrategySelectionScreen
  'select':                         'Seleccionar',
  'strategy':                       'Estrategia',
  'time_limit':                     'Límite de tiempo',
  'welcome_team':                   '¡Bienvenido, equipo!',
  'draw_team_strategy_subtitle':    'Saca tu tarjeta de estrategia y comienza tu misión.',
  'begin_mission':                  'Comenzar misión',

  // ── TeamSuggestionInitiativesScreen
  'suggestion':                     'Sugerencia',
  'of_initiatives':                 'de iniciativas',
  'detail_not_available':           'Detalle no disponible',
  'key_results_missing':            'Faltan datos de resultados clave. Volviendo atrás.',
  'goal':                           'Meta',
  'timeframe':                      'Plazo',
  'select_key_results':             'Seleccionar resultados clave',
  'choose_3_outcomes':              'Elige 3 resultados medibles que definirán el éxito.',
  'first_initiative':               '1ª iniciativa',
  'second_initiative':              '2ª iniciativa',
  'submitting':                     'Enviando...',
  'submit_analysis':                'Enviar análisis',

  // ── Widgets
  'success_rate':                   'Tasa de éxito',
  'level':                          'Nivel',
  'impact':                         'Impacto',
  'performance_breakdown':          'Desglose de rendimiento',
  'total_points':                   'Puntos totales:',
  'rewards_unlocked':               'Recompensas desbloqueadas',
  'badge':                          'Insignia',
  'title':                          'Título',
  'trophy':                         'Trofeo',
  'achievement_summary':            'Resumen de logros',
  'final_score':                    'Puntuación final',
  'bonus_mode':                         'Modo Bonus',
  'score':                              'Puntuación',
  'continue':                           'Continuar',
  'days':                               'Días',
  'error':                              'Error',
  'streak':                             'Racha',

  // BonusScenarioLoadingScreen
  'generating_scenario':                'Generando escenario',
  'ai_creating_scenario':               'La IA está creando tu escenario...',
  'based_on_role_industry':             'Basado en tu rol e industria',

  // DailyTrainingHomeScreen
  'daily_okr_training':                 'Entrenamiento OKR Diario',
  'daily_training_subtitle':            'Desarrolla tus habilidades OKR cada día',
  'current_streak':                     'Racha actual',
  'already_played_today':               '¡Ya completaste el entrenamiento de hoy!',
  'come_back_tomorrow':                 'Vuelve mañana para mantener tu racha.',
  'todays_challenge':                   'Desafío de hoy',
  'apply_okr_principles':               'Aplica los principios OKR a un escenario real',
  'start_training':                     'Comenzar entrenamiento',

  // CasePresentationScreen
  'todays_case':                        'Caso de hoy',
  'industry':                           'Industria',
  'banking':                            'Banca',
  'vision':                             'Visión',
  'leading_digital_bank':               'Convertirse en el banco digital líder de la región',
  'strategy':                           'Estrategia',
  'strategy_description':               'Transformación digital y excelencia operacional',
  'problems_faced':                     'Problemas encontrados',
  'digital_outages':                    'Interrupciones digitales frecuentes que afectan la confianza del cliente',
  'high_operational_costs':             'Altos costos operativos que reducen la rentabilidad',
  'slow_staff_adoption':                'Adopción lenta del personal a las nuevas herramientas digitales',
  'define_objective':                   'Definir objetivo',

  // ObjectiveInputScreen
  'step_1_objective':                   'Paso 1: Objetivo',
  'write_one_ambitious_objective':      'Escribe un objetivo ambicioso para este escenario',
  'objective_hint':                     'Piensa en grande — ¿qué debe lograr esta empresa?',
  'example_objective':                  'ej. Convertirse en el banco digital más centrado en el cliente para Q4',
  'next_key_results':                   'Siguiente: Resultados clave',
  'please_enter_objective':             'Por favor ingresa un objetivo',

  // KeyResultsInputScreen
  'step_2_key_results':                 'Paso 2: Resultados clave',
  'define_two_measurable_krs':          'Define 2 Resultados Clave medibles',
  'kr_hint':                            'Cada RC debe ser específico, medible y con límite de tiempo',
  'key_result_1':                       'Resultado Clave 1',
  'key_result_2':                       'Resultado Clave 2',
  'example_kr_1':                       'ej. Reducir las interrupciones del sistema de 5% a 0.5% para Q3',
  'example_kr_2':                       'ej. Aumentar el volumen de transacciones digitales en 40% para Q4',
  'next_initiative':                    'Siguiente: Iniciativa',
  'please_fill_key_results':            'Por favor completa todos los resultados clave',

  // InitiativeInputScreen
  'step_3_initiative':                  'Paso 3: Iniciativa',
  'propose_one_actionable_initiative':  'Propone una iniciativa concreta',
  'initiative_hint':                    '¿Qué acción concreta impulsará estos resultados?',
  'example_initiative':                 'ej. Lanzar un chatbot de IA 24/7 para soporte al cliente',
  'submit_for_ai_evaluation':           'Enviar para evaluación IA',
  'please_enter_initiative':            'Por favor ingresa una iniciativa',

  // EvaluationLoadingScreen
  'evaluating_subtitle':                'Evaluando tu OKR',
  'ai_evaluating_okr':                  'La IA está evaluando tu OKR...',
  'checking_quality_alignment_relevance': 'Verificando calidad, alineación y relevancia',

  // ScoringBreakdownScreen
  'evaluation_results':                 'Resultados de la evaluación',
  'overall_score':                      'Puntuación general',
  'excellent_performance':              '¡Rendimiento excelente!',
  'good_performance':                   'Buen rendimiento',
  'detailed_breakdown':                 'Desglose detallado',
  'objective_quality':                  'Calidad del objetivo',
  'key_results_quality':                'Calidad de los resultados clave',
  'initiative_impact':                  'Impacto de la iniciativa',
  'global_alignment':                   'Alineación global',
  'contextual_relevance':               'Relevancia contextual',
  'see_feedback':                       'Ver retroalimentación',

  // FeedbackBonusScreen
  'ai_feedback':                        'Retroalimentación de IA',
  'strengths':                          'Fortalezas',
  'improvements':                       'Mejoras',
  'view_badge_reward':                  'Ver insignia ganada',

  // BadgeRewardScreen
  'badge_reward_subtitle':              '¡Ganaste una insignia!',
  'badge_earned':                       '¡Insignia ganada!',

  // TrainingCompleteScreen
  'training_completed':                 '¡Entrenamiento completado!',
  'today_score':                        'Puntuación de hoy',
  'obtained_score':                     'Insignia',
  'low_score_streak_not_increment':     'Puntuación menor a 60 — racha no actualizada. ¡Sigue practicando!',
  'great_job_streak_increment':         '¡Excelente! Tu racha ha sido actualizada.',
  'see_you_tomorrow':                   '¡Hasta mañana! 🎯',
  'back_to_home':                       'Volver al inicio',

// ── General / Shared ──────────────────────────────────────────────────────
  'ok':                           'Aceptar',
  'no':                           'No',
  'yes':                          'Sí',
  'error':                        'Error',
  'continue':                     'Continuar',
  'final_score':                  'Puntuación final',
  'loading_data':                 'Cargando datos...',
  'please_wait':                  'Por favor espera...',
  'retry':                        'Intento',
  'of':                           'de',
  'analyzing':                    'Analizando...',
  'submitting':                   'Enviando...',
  'save_changes':                 'Guardar cambios',
  'complete_selection':           'Completar selección',

  // ── Home Screen ───────────────────────────────────────────────────────────
  'certificate':                  'Certificado',
  'bonus_mode':                   'Modo Bonificación',
  'go_to':                        'Ir al',
  'dashboard':                    'Panel',
  'daily_bonus_complete':         '¡Bonificación diaria completada!',
  'already_played_today':         'Ya has jugado al modo bonificación hoy.',
  'your_score_today':             'Tu puntuación de hoy',
  'come_back_tomorrow':           '¡Vuelve mañana para un nuevo desafío!',
  'failed_start_bonus':           'Error al iniciar el modo bonificación: ',

  // ── Role Selection ────────────────────────────────────────────────────────
  'select':                       'Seleccionar',
  'role':                         'Rol',
  'welcome_navigator':            '¡Bienvenido, Navegante!',
  'company_crisis_description':   'Tu empresa enfrenta un desafío crítico. Como tomador de decisiones clave, tus elecciones estratégicas determinarán el futuro de la organización.',
  'choose_role_instruction':      'Elige tu rol para comenzar tu viaje estratégico.',
  'select_your_role':             'Selecciona tu rol',
  'first_time_playing':           '¿Primera vez?',
  'watch_tutorial':               'Ver tutorial',

  // ── Choose Industry ───────────────────────────────────────────────────────
  'choose':                       'Elegir',
  'your_industry':                'Tu Industria',
  'search_industry':              'Buscar industria...',

  // ── Strategy Selection ────────────────────────────────────────────────────
  'strategy':                     'Estrategia',
  'selection':                    'Selección',
  'draw_strategy':                'Elige tu Estrategia',
  'draw_strategy_subtitle':       'Selecciona la carta estratégica que mejor se alinee con tu visión y objetivos.',
  'begin_mission':                'Iniciar misión',

  // ── Key Objective Selected ────────────────────────────────────────────────
  'objective':                    'Objetivo',
  'choose_your_objective':        'Elige tu objetivo',
  'select_one_objective':         'Selecciona un objetivo en el que enfocarte.',
  'selected_strategy':            'Estrategia seleccionada',
  'try_again_with_different':     'Intentar con diferente',
  'modify':                       'Modificar',
  'select_different_objective_retry':   'Selecciona un objetivo diferente para mejorar tus iniciativas.',
  'select_new_objective_for_challenge': 'Selecciona un nuevo objetivo para adaptarte al desafío del mercado.',
  'retry_attempt':                'Intento de reintento',
  'adapting_to_challenge':        'Adaptándose al desafío',

  // ── Key Results ───────────────────────────────────────────────────────────
  'key_results':                  'Resultados clave',
  'select_key_results':           'Seleccionar resultados clave',
  'choose_3_outcomes':            'Elige 3 resultados clave alineados con tu objetivo.',
  'choose_3_outcomes_retry':      'Elige 3 resultados clave diferentes para mejorar tu puntuación.',
  'choose_3_outcomes_modify':     'Elige 3 nuevos resultados clave para adaptar tu estrategia.',
  'generating_key_results':       'Generando resultados clave...',
  'available_key_results':        'Resultados clave disponibles',
  'selected_objective':           'Objetivo seleccionado',
  'try_again_with':               'Intentar de nuevo con',
  'exit_selection':               '¿Salir de la selección?',
  'exit_selection_confirmation':  '¿Estás seguro de que deseas salir? Tu progreso se perderá.',

  // ── Feedback Screen ───────────────────────────────────────────────────────
  'okr':                          'OKR',
  'feedback':                     'Retroalimentación',
  'no_feedback_data_available':   'No hay datos de retroalimentación disponibles.',
  'submitting_bonus_score':       'Enviando puntuación de bonificación...',
  'bonus_score_submitted':        '¡Puntuación de bonificación enviada: %score% pts!',
  'bonus_mode_active':            'Modo Bonificación Activo',
  'score':                        'Puntuación total: %0',
  'strategy_alignment':           'Alineación estratégica',
  'objective_alignment':          'Alineación de objetivos',
  'key_result_quality':           'Calidad de resultados clave',
  'okr_evaluation_feedback':      'Retroalimentación de evaluación OKR',
  'bonus_mode_completed':         '¡Modo Bonificación completado!',
  'bonus_mode_completion_message':'¡Excelente trabajo! Vuelve mañana para un nuevo desafío.',

  // ── Suggestion Initiatives ────────────────────────────────────────────────
  'suggestion':                   'Sugerencia',
  'of_initiatives':               'de iniciativas',
  'review':                       'Revisión',
  'initiatives':                  'Iniciativas',
  'first_initiative':             '1.ª Iniciativa',
  'second_initiative':            '2.ª Iniciativa',
  'submit_analysis':              'Enviar para análisis de IA',
  'continue_to_adaptation':       'Continuar hacia la adaptación',
  'strategic_initiative':         'Iniciativa estratégica',
  'add_initiatives_to_continue':  'Agrega tus iniciativas para continuar.',
  'selected_key_result':          'Resultado clave seleccionado',
  'user_initiatives':             'Tus iniciativas',
  'current_focus':                'Enfoque actual',

  // ── AI Analysis Show Screen ───────────────────────────────────────────────
  'adaptation':                   'Adaptación',
  'analysis':                     'Análisis',
  'try_again':                    'Intentar de nuevo',
  'check_contextual_challenge':   'Ver desafío contextual',
  'proceed_to_results':           'Ir a resultados',
  'relevance_threshold':          'Umbral de relevancia',
  'loading_analysis':             'Analizando iniciativas...',
  'initiative_rejected':          'Iniciativa rechazada',
  'initiative_needs_improvement': 'Tu iniciativa necesita mejoras.',
  'retry_count':                  'Número de intentos',
  'suggest_improve_initiatives':  'Por favor, selecciona objetivos y resultados clave diferentes.',
  'max_retries_reached':          'Número máximo de intentos alcanzado',
  'max_retries_exceeded':         'Has usado los 3 intentos.',
  'returning_to_home_screen':     'Volviendo a la pantalla de inicio.',
  'understand':                   'Entiendo',

  // ── CustomAIStrategyContainer ─────────────────────────────────────────────
  'ai_strategic_analysis':          'Análisis Estratégico de IA',
  'submit_initiatives_ai_analysis': 'Envía tus iniciativas para recibir un análisis estratégico impulsado por IA.',
  'feedback_will_appear_here':      'La retroalimentación aparecerá aquí después del envío.',
  "ready_for_solo_mode": "¿Listo para el modo Solo?",
  "ready_for_team_mode": "¿Listo para el modo Equipo?",
  "ready_for_campaign_mode": "¿Listo para el modo Campaña?",
  "solo_mode_description": "Desafíate y mejora tus habilidades individualmente con nuestras funciones de modo solo.",
  "team_mode_description": "Colabora con los miembros de tu equipo y alcanza objetivos comunes.",
  "campaign_mode_description": "Embárcate en un emocionante viaje con misiones estructuradas y desafíos progresivos.",

  "solo_mode_level_1": "Acceso al Nivel 1 del modo Solo",
  "ai_feedback_per_day": "Retroalimentación IA (3 por día)",
  "certified_challenge_per_day": "Desafío certificado (1 por día)",
  "limited_badges": "Colección de insignias limitada",
  "full_solo_mode": "Acceso completo al modo Solo",
  "weekly_missions": "Misiones semanales",
  "ai_tips_debrief": "Consejos y informe IA",
  "xp_tracking": "Seguimiento de XP",
  "community_leaderboard": "Tabla de clasificación comunitaria",
  "bonus_mode": "Acceso al modo Bonus",
  "all_navigator_plus_features": "Todas las funciones de Navigator+",
  "official_certificate": "Certificado oficial",
  "performance_reports": "Informes de rendimiento",
  "monthly_live_coaching": "Entrenamiento en vivo mensual",
  "exclusive_badge_sets": "Conjuntos de insignias exclusivas",

  "level_1_access": "Acceso Nivel 1",
  "level_2_access": "Acceso Nivel 2",
  "level_3_access": "Acceso Nivel 3",
  "single_user": "Usuario único",
  "multiple_users": "Múltiples usuarios",


  "ready_for_solo_mode": "¿Listo para el modo Solo?",
  "ready_for_team_mode": "¿Listo para el modo Equipo?",
  "ready_for_campaign_mode": "¿Listo para el modo Campaña?",
  "solo_mode_description": "Desafíate y mejora tus habilidades individualmente",
  "team_mode_description": "Trabaja junto con tu equipo para lograr objetivos comunes",
  "campaign_mode_description": "Participa en misiones estructuradas con dificultad progresiva",
  'select':                          'Seleccionar',
  'role':                            'Rol',
  'welcome_navigator':               'Bienvenido, Navegante',
  'company_crisis_description':      'Tu empresa está enfrentando una crisis. Navega por los desafíos, toma decisiones estratégicas y lidera a tu equipo hacia el éxito.',
  'choose_role_instruction':         'Elige tu rol para comenzar el recorrido',
  'select_your_role':                'Selecciona tu rol',
  'select_continue':                 'Continuar',
  'first_time_playing':              '¿Es tu primera vez jugando?',
  'watch_tutorial':                  'Ver tutorial',
  'watch_tutorial_video':            'Ver video del tutorial',
  'select_role':                     'Seleccionar rol',

  'Choose':                          'Elegir',
  'Your Industry':                   'Tu Industria',
  'search_industry':                 'Buscar industria...',
  'choose_industry':                 'Elegir industria',
  'welcome_role':                    'Bienvenido, @role',

  'choose':                          'Elegir',
  'objective':                       'Objetivo',
  'try_again_with_different':        'Intentar de nuevo',
  'modify':                          'Modificar',
  'select_different_objective_retry':'Selecciona un objetivo diferente e inténtalo de nuevo',
  'select_new_objective_for_challenge': 'Selecciona un nuevo objetivo para adaptarte al desafío actual',
  'select_one_objective':            'Selecciona un objetivo para guiar tu estrategia',
  'save_changes':                    'Guardar cambios',
  'complete_selection':              'Completar selección',
  'selected_strategy':               'Estrategia seleccionada',
  'choose_your_objective':           'Elige tu objetivo',
  'retry_attempt':                   'Intento de reintento',
  'adapting_to_challenge':           'Adaptándose al desafío',
  'no_objectives_available':         'No hay objetivos disponibles',

  'tap_to_reveal_strategy':          'Toca para revelar la estrategia',
  'draw_new_strategy':               'Sacar nueva estrategia',
  // APP NAME & LOGOS
  "app_name": "OKR Navigator",
  "okr_nav": "OKR'Nav",
  "okr_hau": "OKR'hau",
  "okr_now": "OKR'Now",
  "okr_logo": "Logo OKR",
  "bottom_logo": "Logo de la app",
  "progress_warning": "Advertencia de Progreso",
  "progress_warning_desc": "Tu progreso actual se perderá. ¿Estás seguro de que quieres ir a casa?",
  "cancel": "Cancelar",
  "yes_go_home": "Sí, Ir a Casa",
  "success": "Éxito",
  "redirected_home": "Redirigido a la pantalla de inicio",
  // Feedback Screen
  'choose_industry': 'Elige tu industria',
  'strategic_initiative': 'Iniciativa estratégica',
  'add_initiatives_to_continue': 'Agrega iniciativas para continuar',
  "okr": "OKR",
  "feedback": "Retroalimentación",
  "no_feedback_data_available": "No hay datos de retroalimentación disponibles",
  "continue": "Continuar",
  "level_completed": "¡Nivel Completado!",
  "organization_completed": "¡Organización ${0} completada!",
  "score": "Puntuación: ${0}",
  "strategy_alignment": "Alineación Estratégica",
  "objective_alignment": "Alineación de Objetivos",
  "key_result_quality": "Calidad de Resultados Clave",
  "okr_evaluation_feedback": "Retroalimentación de Evaluación OKR",
  
  // Language Screen
  "choose_language": "Elige tu idioma",
  "language_subtitle": "Selecciona tu idioma preferido para la aplicación",
  "continue_button": "Continuar",
  "english": "Inglés",
  "spanish": "Español",
  "french": "Francés",
  "german": "Alemán",
  "italian": "Italiano",
  "afrikaans": "Afrikáans",
  
  // Home Screen
  "certificate": "Certificado",
  
  // Scoreboard Screen
  "your": "Tu",
  "scoreboard": "Tablero de Puntuación",
  "show_personal_achievements": "Mostrar Logros Personales",
  "I'm ranked #3 in Strategic Agility this week!": "¡Estoy clasificado #3 en Agilidad Estratégica esta semana!",
  
  // Team Initiative Screen
  "suggestion": "Sugerencia",
  "of_initiatives": "de Iniciativas",
  "error": "Error",
  
  // Personal Achievements Screen
  "personal": "Personal",
  "achievements": "Logros",
  "strategic_architect": "Arquitecto Estratégico",
  "level": "Nivel {{num}}",
  "points": "Puntos",
  
  // Final Test Certification Screen
  "final_test": "Examen Final",
  "certification": "Certificación",
  "ai_evaluation_progress": "Progreso de Evaluación IA",
  "test_completed": "Prueba Completada",
  
  // Mini Simulation Screen
  "mini_simulation": "Mini Simulación",
  "refine_strategy_address_challenge": "Refina tu estrategia para abordar el desafío",
  "solve_scenario_minutes": "Resuelve este escenario en solo unos minutos",
  
  // Game Complete Screen
  "game": "Juego",
  "complete": "Completado",

  // AUTHENTICATION & ONBOARDING
  "dont_have_account": "¿No tienes una cuenta?",
  "already_have_account": "¿Ya tienes una cuenta?",
  "alreadyNavigator": "¿Ya eres Navegador?",
  "login": "Iniciar sesión",
  "register": "Registrarse",
  "logout": "Cerrar sesión",
  "sign_in": "Iniciar sesión",
  "sign_up": "Registrarse",
  "want_a_navigator": "¿Quieres un Navegador?",
  "sign_up_role": "Regístrate para asumir el papel de Navegador estratégico.",
  "signUpRole": "Regístrate para asumir el papel de Navegador estratégico.",
  "enter_arena": "Entrar en la Arena OKR",
  "rejoin_operation": "Reanudar la Operación",
  "strategy_awaits": "Tu estrategia te espera. Inicia sesión para continuar.",
  "remember_me": "Recordarme",
  "forget_password": "¿Olvidaste tu contraseña?",
  "password_reset_coming": "¡La función de restablecer contraseña llegará pronto!",
  "email": "Ingresar correo electrónico",
  "enter_email": "Ingresar dirección de correo",
  "password": "Ingresar contraseña",
  "enter_password": "Ingresar contraseña",
  "confirm_password": "Confirmar contraseña",
  "enter_confirm_password": "Confirmar contraseña",
  "enter_name": "Ingresar nombre",
  "enter_phone": "Ingresar número de teléfono",

  // FORM VALIDATION
  "email_required": "El correo es obligatorio",
  "invalid_email": "Por favor, introduce un correo válido",
  "password_required": "La contraseña es obligatoria",
  "password_length": "La contraseña debe tener al menos 6 caracteres",
  "password_mismatch": "Las contraseñas no coinciden",
  "name_required": "El nombre es obligatorio",
  "phoneRequired": "El teléfono es obligatorio",
  "invalidPhone": "Por favor, introduce un teléfono válido",

  // AUTH MESSAGES
  "invalid_credentials": "Correo o contraseña incorrectos",
  "login_failed": "Error al iniciar sesión. Inténtalo de nuevo.",
  "login_successful": "¡Inicio de sesión exitoso!",
  "registration_successful": "¡Registro exitoso!",
  "registration_failed": "Error de registro. Inténtalo de nuevo.",
  "email_not_found": "Correo no encontrado",
  "invalid_password": "Contraseña inválida",

  // LANGUAGE & LOCALIZATION
  "select_language": "Seleccionar idioma",
  "choose_language": "Elige tu idioma preferido",
  "currentLanguage": "Idioma actual",
  "english": "Inglés",
  "spanish": "Español",
  "french": "Francés",
  "german": "Alemán",
  "italian": "Italiano",
  "russian": "Ruso",

  // COMMON BUTTONS & STATES
  "continue": "Continuar",
  "next": "Siguiente",
  "back": "Atrás",
  "skip": "Saltar",
  "done": "Hecho",
  "loading": "Cargando...",
  "retry": "Reintentar",
  "no_data": "No hay datos disponibles",
  "coming_soon": "¡Esta función estará disponible pronto!",
  "ok": "OK",
  "cancel": "Cancelar",

  // HOME & DASHBOARD
  "home": "Inicio",
  "profile": "Perfil",
  "settings": "Configuraciones",
  "notifications": "Notificaciones",
  "dashboard": "Panel de control",

  // STRATEGY SCREENS
  "strategy": "Estrategia",
  "draw_strategy": "Dibuja tu estrategia",
  "draw_strategy_subtitle": "Dibuja tu tarjeta de estrategia y da el primer paso\npara remodelar el futuro de la empresa.",
  "strategy_tips": "Consejos de estrategia",
  "strategic_tips": "Consejos estratégicos",
  "draw_new_strategy": "Dibujar nueva estrategia",
  "tap_to_reveal_strategy": "Toca para revelar tu estrategia",
  "strategy_intro": "Acabas de entrar en una empresa en crisis. Cada decisión puede cambiar su futuro.",
  "strategy_tip1": "Desarrollar e introducir productos innovadores",
  "strategy_tip2": "Enfocarse en expandirse a mercados no explotados para impulsar el crecimiento sostenible y aumentar la participación en el mercado.",

  // AI STRATEGIC ANALYSIS
  "ai_strategic_analysis": "Análisis estratégico de IA",
  "submit_initiatives_ai_analysis": "Enviar tus iniciativas para análisis de IA",
  "feedback_will_appear_here": "Los comentarios aparecerán aquí",
  "ai_feedback_per_day": "1 comentario de IA por día",
  "ai_tips_debrief": "Consejos de IA y revisión",
  "AI has analyzed your initiatives and found them highly relevant! 🚀":
  "¡La IA ha analizado tus iniciativas y las ha encontrado muy relevantes! 🚀",

  // OBJECTIVES & KEY RESULTS
  "objective": "Objetivo",
  "selected_objective": "Objetivo seleccionado",
  "objective_description":
  "''Desarrollar e introducir productos innovadores\n"
      "adaptados a las nuevas demandas del mercado en 15\n"
      "meses''",
  "select_key_results": "Seleccionar resultados clave",
  "choose_3_outcomes": "Elige 3 resultados medibles. Construye tu\nconstelación de métricas de éxito",
  "complete_selection": "Completar selección",
  "key_results_selected": "Resultados clave seleccionados",
  "all_key_results_selected": "¡Todos los resultados clave seleccionados!",
  "one_more_needed": "Falta 1 más",
  "more_needed": "faltan más",

  // INDUSTRY SELECTION
  'Select Industry': 'Seleccionar industria',
  'Please select an industry to continue': 'Por favor selecciona una industria para continuar',
  'Selected': 'Seleccionado',
  'You selected:': 'Has seleccionado:',
  'Technology': 'Tecnología',
  'Software, SaaS, Digital Products': 'Software, SaaS, Productos digitales',
  'Finance & Banking': 'Finanzas y Banca',
  'Investment, Insurance, Fintech': 'Inversión, Seguros, Fintech',
  'Healthcare': 'Salud',
  'Medical, Pharma, Health Tech': 'Médico, Farmacéutico, Tecnología de la Salud',

  // GAME MODES
  "game_mode": "Modo de juego",
  "unknown_mode": "Modo desconocido",
  "solo": "Individual",
  "Solo": "Individual",
  "Team": "Equipo",
  "Campaign": "Campaña",
  "bonus_mode": "Modo bonus",
  "navigator": "Navegador",
  "navigator_plus": "Navegador+",
  "master_navigation": "Navegación maestra",

  // ONBOARDING & MISC SCREENS
  "welcome_navigator": "¡Bienvenido, Navegador!",
  "splash1_subtitle": "Has sido reclutado para una misión de alto riesgo. "
      "Una de nuestras empresas más importantes enfrenta una crisis estratégica "
      "y necesita tu liderazgo para cambiar las cosas.",
  "splash2_title": "La empresa está en problemas",
  "splash2_subtitle": "La productividad está disminuyendo. Los objetivos están desalineados. "
      "El equipo está perdiendo el enfoque. Solo tú tienes las habilidades "
      "para aportar claridad, dirección y resultados.",

  // JOURNEY & MAP
  "journey": "Viaje",
  "map": "Mapa",
  "show_less": "Mostrar menos",
  "show_progress": "Mostrar progreso",
  "complete": "Completado",
  "back_home": "Volver al inicio",

  // ERRORS
  "error": "Error",
  "fill_initiatives": "Por favor, completa ambas iniciativas antes de enviar.",
  "initiatives_submitted": "✅ Iniciativas enviadas para análisis de IA.",
  'show_personal_achievements': 'Show Personal Achievements',
};
